services:
  protocolo:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: hackaton-pague-menos
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    
